[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build && npx prisma generate"

[deploy]
startCommand = "pnpm run start:prod"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
